OBS_App/Areas/Admin/Controllers/DuyuruController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OBS_App.Data;
using OBS_App.Hubs;
using OBS_App.Models;
namespace OBS_App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DuyuruController : Controller
    {
        private readonly IdentityDataContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IHubContext<SignalRHub> _hubContext;

        public DuyuruController(IdentityDataContext context, UserManager<AppUser> userManager, IHubContext<SignalRHub> hubContext)
        {
            _userManager = userManager;
            _context = context;
            _hubContext = hubContext;
        }
        public async Task<IActionResult> Index()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            var bildirim = await _context.Bildirimler.Where(x => x.BildirimEposta == kullanıcı.Email).ToListAsync();

            foreach (var bld in bildirim)
            {
                bld.BildirimOkunma = true;
            }
            _context.Bildirimler.UpdateRange(bildirim);
            _context.SaveChanges();

            var duyurular = await _context.Duyurular.Include(x => x.Ogretmens).ToListAsync();
            return View(duyurular);
        }

        public async Task<IActionResult> Ekle_Guncelle(int id)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                var duyuru = await _context.Duyurular.FirstOrDefaultAsync(x => x.Id == id);
                if (duyuru == null)
                {
                    // Hata Gönder
                    return RedirectToAction("Index");
                }
                return View(duyuru);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Ekle_Guncelle(int id, Duyuru model)
        {

            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    var kullanıcı = await _userManager.GetUserAsync(User);
                    var eposta = await _userManager.Users.Where(x => x.Email != kullanıcı.Email).ToListAsync();

                    foreach (var item in eposta)
                    {
                        await _context.Bildirimler.AddAsync(new Bildirim
                        {
                            BildirimBaslik = model.DuyuruBaslik,
                            BildirimDuyuru = model.DuyuruMesaj,
                            BildirimEposta = item.Email,
                        });
                    }

                    await _hubContext.Clients.All.SendAsync("AdminDuyuru", model.DuyuruBaslik, model.DuyuruMesaj);
                    await _context.Duyurular.AddAsync(model);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Kayıt eklendi.";
                    return RedirectToAction("Index");
                }
                else
                {
                    _context.Duyurular.Update(model);
                    _context.SaveChanges();
                    TempData["success"] = "Kayıt güncellendi.";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(model);
            }
        }

        public IActionResult Sil(int id)
        {
            var duyuru = _context.Duyurular.FirstOrDefault(x => x.Id == id);
            if (duyuru != null)
            {
                _context.Remove(duyuru);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Bildirim(int id)
        {
            var user = _userManager.GetUserAsync(User).Result;
            var bildirim = await _context.Bildirimler.Where(x => x.BildirimEposta == user.Email).ToListAsync();

            var okundu = await _context.Bildirimler.FirstOrDefaultAsync(x => x.Id == id);
            if (okundu != null)
            {
                okundu.BildirimOkunma = true;
                _context.Bildirimler.Update(okundu);
                await _context.SaveChangesAsync();

            }
            return Json(bildirim);
        }

        [HttpPost]
        public async Task<IActionResult> Bildirim()
        {
            var user = _userManager.GetUserAsync(User).Result;
            var bildirim = await _context.Bildirimler.Where(x => x.BildirimEposta == user.Email).ToListAsync();
            _context.Bildirimler.RemoveRange(bildirim);
            await _context.SaveChangesAsync();
            return Json(bildirim);
        }       
    }
}

OBS_App/Areas/Admin/Controllers/TakvimController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OBS_App.Data;
using OBS_App.Models;

namespace OBS_App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class TakvimController : Controller
    {
        private readonly IdentityDataContext _context;
        public TakvimController(IdentityDataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var takvimler = await _context.AkademikTakvimler.ToListAsync();

            return View(takvimler);

        }

        public async Task<IActionResult> Ekle_Guncelle(int id)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                var takvim = await _context.AkademikTakvimler.FirstOrDefaultAsync(x => x.Id == id);
                return View(takvim);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Ekle_Guncelle(AkademikTakvim model, int id)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    await _context.AkademikTakvimler.AddAsync(model);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Kayıt eklendi.";
                    return RedirectToAction("Index");

                }
                //Güncelleme işlemi
                else
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Kayıt güncellendi.";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(model);
            }
        }


        public async Task<IActionResult> Sil(int? id)
        {

            if (id != null)
            {
                var user = await _context.AkademikTakvimler.FirstOrDefaultAsync(u => u.Id == id);
                if (user != null)
                {
                    _context.Remove(user);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");

                }
            }
            return View();
        }

    }
}

OBS_App/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-comman w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-info">
                        <h6>Öğrenciler</h6>
                        <h3>@ViewBag.ogrenci_sayısı</h3>
                    </div>
                    <div class="db-icon">
                        <img width="60px" src="https://cdn3d.iconscout.com/3d/premium/thumb/male-graduate-student-9638045-7889079.png" alt="Dashboard Icon">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12 d-flex" onclick="resetNotificationCount()">
        <div class="card bg-comman w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-info">
                        <h6>Öğretmenler</h6>
                        <h3>@ViewBag.ogretmen_sayısı</h3>
                    </div>
                    <div class="db-icon">
                        <img width="60px" src="https://cdn3d.iconscout.com/3d/premium/thumb/male-teacher-10074802-8187379.png" alt="Dashboard Icon">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-comman w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-info">
                        <h6>Bölümler</h6>
                        <h3>@ViewBag.bolum_sayısı</h3>
                    </div>
                    <div class="db-icon">
                        <img width="60px" src="https://cdn3d.iconscout.com/3d/premium/thumb/geography-book-8013528-6430667.png" alt="Dashboard Icon">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-comman w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-info">
                        <h6>Fakülteler</h6>
                        <h3>@ViewBag.fakulte_sayısı</h3>
                    </div>
                    <div class="db-icon">
                        <img width="70px" src="https://cdn3d.iconscout.com/3d/premium/thumb/school-building-9609721-7762972.png" alt="Dashboard Icon">
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12 col-lg-6">

        <div class="card card-chart">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col-6">
                        <h5 class="card-title">Bölümlere Göre Öğrenci Sayıları</h5>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div id="s-bar"></div>
            </div>
        </div>

    </div>
    <div class="col-md-12 col-lg-6">

		<div class="card card-chart">
			<div class="card-header">
				<div class="row align-items-center">
					<div class="col-6">
						<h5 class="card-title">Öğrenci Cinsiyetleri Sayısı</h5>
					</div>
					<div class="col-6">
						<ul class="chart-list-out">
							<li><span class="circle-dark_blue"></span>Erkekler</li>
							<li><span class="circle-pink"></span>Kadınlar</li>
							<li class="star-menus"><a href="javascript:;"><i class="fas fa-ellipsis-v"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div id="admin_bar"></div>
			</div>
		</div>

    </div>
</div>

<div class="row">
    <div class="col-xl-6 d-flex">

        <div class="card flex-fill student-space comman-shadow">
            <div class="card-header d-flex align-items-center">
                <h5 class="card-title">Son Akademik Etkinlikler</h5>
                <ul class="chart-list-out student-ellips">
                    <a asp-controller="Takvim" asp-action="Ekle_Guncelle" asp-route-id="0" style="margin-right:20px" class="btn btn-primary btn-sm">Etkinlik Ekle</a>
                </ul>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table star-student table-hover table-center table-borderless table-striped">
                        <thead class="thead-light">
                            <tr>
                                <th class="text-center">Başlangıç Tarihi</th>
                                <th class="text-center">Bitiş Tarihi</th>
                                <th class="text-center">Aktivite</th>
                            </tr>
                        </thead>
                        <tbody>

							@foreach (var etkinlik in ViewBag.takvim)
							{
								<tr>
									<td class="text-center">@etkinlik.AkademikTakvimBaslangic</td>
									<td class="text-center">@etkinlik.AkademikTakvimBitis</td>
									<td>@etkinlik.AkademikTakvimAktivite</td>
								</tr>
							}
							

						</tbody>
					</table>
				</div>
				@if (ViewBag.takvim.Count == 0)
				{
					<br>
					<h5 class="text-danger" style="text-align:center"> Akademik Etkinlik Bulunmamaktadır! </h5>
				}
			</div>
		</div>

    </div>

    @* Duyru Kısmı *@
    <div class="col-xl-6 d-flex">

        <div class="card flex-fill comman-shadow">
            <div class="card-header d-flex align-items-center">
                <h5 class="card-title ">Son Duyurular </h5>
                <ul class="chart-list-out student-ellips">
                    <a asp-controller="Duyuru" asp-action="Index" style="margin-right:20px" class="btn btn-primary btn-sm">Tüm Duyurular</a>
                </ul>
            </div>
            <div class="card-body">
                <div class="activity-groups">

                    @if (ViewBag.duyurular != null)
                    {
                        @foreach (var duyuru in ViewBag.duyurular)
                        {
                            <div class="activity-awards">
                                <div class="award-boxs">
                                    <img width="30px" src="~/panel/img/icons/award-icon-03.svg">
                                </div>
                                <div class="award-list-outs">
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#duyuruModal_@duyuru.Id">@duyuru.DuyuruBaslik</a>
                                    <h5 class="duyuruMesaj">@duyuru.DuyuruMesaj</h5>
                                </div>
                                <div style="text-align:center; display: flex; justify-content: center;" class="award-time-list">
                                    <div class="col">
                                        <span>@duyuru.OlusturmaTarihi</span>
                                        <br>
                                    </div>
                                </div>
                            </div>
                            //Modal
                            <div class="modal fade text-center" id="duyuruModal_@duyuru.Id" tabindex="-1" role="dialog" data-bs-toggle="modal" data-bs-target="#duyuruModal_@duyuru.Id" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div style="background-color:ghostwhite; border-radius:20px" class="modal-content">
                                        <div style="background-color:royalblue;" class="modal-header">
                                            <h5 style="flex: 50%; color:aliceblue" class="modal-title" id="duyuruModalLabel_@duyuru.Id">@duyuru.DuyuruBaslik</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <p>@duyuru.DuyuruMesaj</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        }
                    }
                    else
                    {
                        <h5 class="text-danger" style="text-align:center"> Duyuru Bulunmamaktadır! </h5>
                    }

                </div>
            </div>
        </div>

    </div>
</div>
<script>
    function openDuyuruModal(duyuruId) {
        $('#duyuruModal_' + duyuruId).modal('show');
    }
</script>
<script>
    // Her bir duyuru için kısaltılmış mesajları güncelleyen fonksiyon
    function kisaltmaYap(duyuruMesajiElementi) {
        var duyuruMesaji = duyuruMesajiElementi.textContent;

        if (duyuruMesaji.length > 50) {
            duyuruMesajiElementi.textContent = duyuruMesaji.substring(0, 60) + "...";
        }
    }

    // Her bir duyurunun kısaltılmış mesajını güncelleyin
    var duyuruMesajlar = document.querySelectorAll(".duyuruMesaj");
    duyuruMesajlar.forEach(kisaltmaYap);
</script>

@if (TempData["success"] != null)
{
    <script src="~/panel/plugins/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/panel/plugins/sweetalert/sweetalerts.min.js"></script>

    <script>
        var successMessage = "@TempData["success"]";

        Swal.fire({
            title: successMessage,
            icon: "success"
        });
    </script>
}

OBS_App/Areas/Admin/Views/Admin/SifreDegistir.cshtml
@model SifreDegistirViewsModel

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Şifre Değiştir</div>
                <div class="card-body">
                    <form asp-action="SifreDegistir" asp-controller="Admin" method="post">
                        @if (ViewBag.user != null)
                        {
                            <div class="form-group ">
                                <label>Kullanıcı Seç<span class="login-danger">*</span></label>
                                <select asp-for="Eposta" asp-items="ViewBag.user" class="form-control select2">
                                    <option value="">Seçiniz</option>
                                </select>
                                <span asp-validation-for="Eposta" class="text-danger"></span>
                            </div>
                        }
                        <div class="form-group">
                            <label>Şifre <span class="login-danger">*</span></label>
                            <input asp-for="Parola" class="form-control pass-input" type="password">
                            <span asp-validation-for="Parola" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label>Şifre Onayı<span class="login-danger">*</span></label>
                            <div class="input-group">
                                <input asp-for="ParolaOnayla" class="form-control pass-input" type="password">
                                <div class="input-group-append">
                                    <span class="profile-views feather-eye toggle-password"></span>
                                </div> 
                            </div>
                            <span asp-validation-for="ParolaOnayla" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-block " type="submit">Kaydet</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>