OBS_App/Areas/Ogrenci/Controllers/MesajController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OBS_App.Models;

namespace OBS_App.Areas.Ogrenci.Controllers
{
    [Area("Ogrenci")]
    public class MesajController : BaseController
    {
        public MesajController(IdentityDataContext context, UserManager<AppUser> userManager) : base(userManager, context)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MesajGönder()
        {
            return View();
        }
    }
}

OBS_App/Areas/Ogrenci/Views/Mesaj/Index.cshtml
<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Gelen Kutusu</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index-2.html">Dashboard</a></li>
                    <li class="breadcrumb-item active">Gelen Kutusu</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3 col-md-4">
            <div class="compose-btn">
                <a asp-controller="Mesaj" asp-action="MesajGönder" class="btn btn-primary btn-block">
                    Mesaj Gönder
                </a>
            </div>
            <ul class="inbox-menu">
                <li class="active">
                    <a href="#"><i class="fas fa-download"></i>Gelen Kutusu<span class="mail-count">(5)</span></a>
                </li>             
                <li>
                    <a href="#"><i class="far fa-paper-plane"></i>Gönderilen Mesajlar</a>
                </li>
                <li>
                    <a href="#"><i class="far fa-trash-alt"></i>Çöp Kutusu</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-9 col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="email-header">
                        <div class="row">
                            <div class="col top-action-left">
                                <div class="float-start">
                                    <div class="btn-group dropdown-action">
                                        <button type="button" class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">Select <i class="fas fa-angle-down"></i></button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="#">All</a>
                                            <a class="dropdown-item" href="#">None</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Read</a>
                                            <a class="dropdown-item" href="#">Unread</a>
                                        </div>
                                    </div>                                                              
                                    <div class="btn-group dropdown-action mail-search">
                                        <input type="text" placeholder="Search Messages" class="form-control search-message">
                                    </div>
                                </div>
                            </div>
                            <div class="col-auto top-action-right">
                                <div class="text-end">
                                    <button type="button" title="Refresh" data-bs-toggle="tooltip" class="btn btn-white d-none d-md-inline-block"><i class="fas fa-sync-alt"></i></button>
                                    <div class="btn-group">
                                        <a class="btn btn-white"><i class="fas fa-angle-left"></i></a>
                                        <a class="btn btn-white"><i class="fas fa-angle-right"></i></a>
                                    </div>
                                </div>                             
                            </div>
                        </div>
                    </div>
                    <div class="email-content">
                        <div class="table-responsive">
                            <table class="table table-inbox table-hover">
                                <thead>
                                    <tr>
                                        <th colspan="6">
                                            <input type="checkbox" class="checkbox-all">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="unread clickable-row">
                                        <td>
                                            <input type="checkbox" class="checkmail">
                                        </td>
                                        <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                        <td class="name">Envato Account</td>
                                        <td class="subject">Important account security update from Envato</td>
                                        <td></td>
                                        <td class="mail-date">8:42</td>
                                    </tr>
                                    <tr class="clickable-row">
                                        <td>
                                            <input type="checkbox" class="checkmail">
                                        </td>
                                        <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                        <td class="name">Twitter</td>
                                        <td class="subject">HRMS Bootstrap Admin Template</td>
                                        <td></td>
                                        <td class="mail-date">30 Nov</td>
                                    </tr>
                                    <tr class="unread clickable-row">
                                        <td>
                                            <input type="checkbox" class="checkmail">
                                        </td>
                                        <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                        <td class="name">Richard Parker</td>
                                        <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</td>
                                        <td></td>
                                        <td class="mail-date">18 Sep</td>
                                    </tr>
                                    <tr class="clickable-row">
                                        <td>
                                            <input type="checkbox" class="checkmail">
                                        </td>
                                        <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                        <td class="name">John Smith</td>
                                        <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</td>
                                        <td></td>
                                        <td class="mail-date">21 Aug</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

OBS_App/Areas/Ogrenci/Views/Mesaj/MesajGönder.cshtml
<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Mesaj Gönder</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index-2.html">Dashboard</a></li>
                    <li class="breadcrumb-item active">Compose</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-3 col-md-4">
            <ul class="inbox-menu">
                <li class="active">
                    <a asp-controller="Mesaj" asp-action="Index"><i class="fas fa-download"></i>Gelen Kutusu<span class="mail-count">(5)</span></a>
                </li>
                <li>
                    <a href="#"><i class="far fa-paper-plane"></i>Gönderilen Mesajlar</a>
                </li>
                <li>
                    <a href="#"><i class="far fa-trash-alt"></i>Çöp Kutusu</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-9 col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="https://preschool.dreamstechnologies.com/template/inbox.html">
                        <div class="form-group">
                            <input type="email" placeholder="Kime" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="text" placeholder="Konu" class="form-control">
                        </div>
                        <div class="form-group">
<textarea rows="4" class="form-control summernote" placeholder="Mesajınızı buraya girin."></textarea>
                        </div>
                        <div class="form-group mb-0">
                            <div class="text-center">
                                <button class="btn btn-primary"><i class="fas fa-paper-plane m-r-5"></i> <span>Gönder</span></button>
                                <button class="btn btn-danger m-l-5" type="button"> <i class="far fa-trash-alt m-r-5"></i><span>Sil</span></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

</div>