OBS_App/Areas/Ogretmen/Controllers/NotController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OBS_App.Data;
using OBS_App.Models;

namespace OBS_App.Areas.Ogretmen.Controllers
{
    [Area("Ogretmen")]
    public class NotController : BaseController
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IdentityDataContext _context;

        public NotController(UserManager<AppUser> userManager, IdentityDataContext context) : base(userManager, context)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                var ogretmen = _context.Ogretmenler.FirstOrDefault(x => x.OgretmenEposta == kullanıcı.Email);
                var notlar = _context.Notlar
                    .Include(x => x.Ogrencis)
                    .ThenInclude(x => x.Bolum)
                    .Include(x => x.Ogretmens)
                    .Include(x => x.Ders)
                    .Where(x => x.OgretmensId == ogretmen.Id);

                return View(notlar);
            }
            return View();
        }

        public async Task<IActionResult> Ekle_Guncelle(int id)
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                var ogretmen = _context.Ogretmenler.FirstOrDefault(x => x.OgretmenEposta == kullanıcı.Email);
                ViewBag.Dersler = new SelectList(_context.Dersler.Where(x => x.OgretmensId == ogretmen.Id).ToList(), "Id", "DersAd");
                ViewBag.Ogrenciler = new SelectList(_context.Ogrenciler.Where(x => x.BolumId == ogretmen.BolumId).Include(x => x.Ogretmensler).ToList(), "Id", "OgrenciAd");
                ViewBag.OgretmensId = ogretmen.Id;

                if (id == 0)
                {
                    return View();
                }
                else
                {
                    var notlar = _context.Notlar.Include(x => x.Ogrencis).Include(x => x.Ogretmens).Include(x => x.Bolum).FirstOrDefault(x => x.Id == id);
                    return View(notlar);
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Ekle_Guncelle(Not model, int type)
        {
            var existingNot = await _context.Notlar.FirstOrDefaultAsync(n => n.OgrencisId == model.OgrencisId && n.DersId == model.DersId);

            if (ModelState.IsValid)
            {
                if (type == 0 && existingNot == null)
                {
                    await _context.Notlar.AddAsync(model);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Kayıt eklendi!";
                    return RedirectToAction("Index");

                }
                else if (existingNot != null)
                {
                    existingNot.NotOdev= model.NotOdev;
                    existingNot.NotVize= model.NotVize;
                    existingNot.NotFinal = model.NotFinal;

                    existingNot.NotOdevTarih = model.NotOdevTarih;
                    existingNot.NotVizeTarih = model.NotVizeTarih;
                    existingNot.NotFinalTarih = model.NotFinalTarih;

                    existingNot.NotOdevSaat = model.NotOdevSaat;
                    existingNot.NotVizeSaat = model.NotVizeSaat;
                    existingNot.NotFinalSaat = model.NotFinalSaat;

                    _context.Update(existingNot);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Sil(int id)
        {
            var not = _context.Notlar.FirstOrDefault(x => x.Id == id);
            if (not != null)
            {
                _context.Remove(not);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

OBS_App/Areas/Ogretmen/Views/Not/Ekle_Guncelle.cshtml
@model Not
@{
    ViewData["Title"] = "Ekle_Guncelle";
}

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <form asp-controller="Not" asp-action="Ekle_Guncelle" method="post">
                    <input type="hidden" asp-for="OgretmensId" value="@ViewBag.OgretmensId" class="form-control">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="form-title"><span>Not Bilgileri</span></h5>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Ödev Notu</label>
                                <input asp-for="NotOdev" class="form-control" type="number">
                                <span asp-validation-for="NotOdev" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Vize Notu</label>
                                <input asp-for="NotVize" class="form-control" type="number">
                                <span asp-validation-for="NotVize" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Final Notu</label>
                                <input asp-for="NotFinal" class="form-control" type="number">
                                <span asp-validation-for="NotFinal" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <h5 class="form-title"><span>Tarih Bilgileri</span></h5>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Ödev Tarih </label>
                                <input asp-for="NotOdevTarih" class="form-control" type="date">
                                <span asp-validation-for="NotOdevTarih" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Vize Tarih</label>
                                <input asp-for="NotVizeTarih" class="form-control" type="date">
                                <span asp-validation-for="NotVizeTarih" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Final Tarih</label>
                                <input asp-for="NotFinalTarih" class="form-control" type="date">
                                <span asp-validation-for="NotFinalTarih" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <h5 class="form-title"><span>Saat Bilgileri</span></h5>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Ödev Saat </label>
                                <input name="saat" asp-for="NotOdevSaat" class="form-control" type="text">
                                <span asp-validation-for="NotOdevSaat" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Vize Saat </label>
                                <input name="saat" asp-for="NotVizeSaat" class="form-control" type="text">
                                <span asp-validation-for="NotVizeSaat" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Final Saat</label>
                                <input name="saat" asp-for="NotFinalSaat" class="form-control" type="text">
                                <span asp-validation-for="NotFinalSaat" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <h5 class="form-title"><span>Atama Bilgileri</span></h5>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Ders <span class="login-danger">*</span></label>
                                <select asp-for="DersId" asp-items="ViewBag.Dersler" class="form-control select2">
                                    <option value="">Seçiniz</option>
                                </select>
                                <span asp-validation-for="DersId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-sm-4">
                            <div class="form-group local-forms">
                                <label>Öğrenci <span class="login-danger">*</span></label>
                                <select asp-for="OgrencisId" asp-items="ViewBag.Ogrenciler" class="form-control select2">
                                    <option value="">Seçiniz</option>
                                </select>
                                <span asp-validation-for="OgrencisId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="student-submit">
                                @if (Model == null)
                                {
                                    <input name="type" id="type" type="hidden" value="0">
                                }
                                else
                                {
                                    <input name="type" id="type" type="hidden" value="1">
                                }
                                <button type="submit" class="btn btn-primary">Onayla</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

OBS_App/Areas/Ogretmen/Views/Not/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<Not>

<div class="student-group-form">
    <div class="row">
        <div class="col-lg-5 col-md-7">
            <div class="form-group">
                <input type="text" class="form-control" id="ogrenciAdiArama" placeholder="Öğrenci İsmine Göre Ara ..." oninput="aramaYap()">
            </div>
        </div>
        <div class="col-lg-5 col-md-7">
            <div class="form-group">
                <input type="text" class="form-control" id="bolumAdiArama" placeholder="Öğrenci Bölümüne Göre Ara ..." oninput="aramaYap()">
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body">
                <div class="col-auto text-end float-end ms-auto download-grp">
                    <a asp-controller="Not" asp-action="Ekle_Guncelle" asp-route-type="0" class="btn btn-primary"><i class="fas fa-plus"></i> Ekle</a>
                </div>
                <div class="page-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="page-title">Not Bilgileri</h3>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table border-0 star-student table-hover table-center mb-0  table-striped">
                        <thead class="student-thread">
                            <tr>
                                <th>Ad-Soyad</th>
                                <th>Bölüm</th>
                                <th>Ders</th>
                                <th>Sınıf</th>
                                <th>Ödev Notu</th>
                                <th>Vize Notu</th>
                                <th>Final Notu</th>
                                <th class="text-end">İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var not in Model) // Modeldeki her öğrenci için döngü
                            {
                                <tr>
                                    <td>
                                        <h2 class="table-avatar">
                                            <a href="student-details.html" class="avatar avatar-sm me-2"><img class="avatar-img rounded-circle" src="~/img/@not.Ogrencis?.OgrenciFotograf" alt="User Image"></a>
                                            <a href="student-details.html">@not.Ogrencis?.OgrenciAd @not.Ogrencis?.OgrenciSoyad</a>
                                        </h2>
                                    </td>
                                    <td>@not.Ogrencis?.Bolum?.BolumAd</td>
                                    <td>@not.Ders?.DersAd</td>
                                    <td>@not.Ogrencis?.OgrenciSinif</td>
                                    @if (not.NotOdev != null)
                                    {
                                        <td>@not.NotOdev</td>
                                    }
                                    else
                                    {
                                        <td>Not Girilmedi</td>
                                    }
                                    @if (not.NotVize != null)
                                    {
                                        <td>@not.NotVize</td>
                                    }
                                    else
                                    {
                                        <td>Not Girilmedi</td>
                                    }
                                    @if (not.NotFinal != null)
                                    {
                                        <td>@not.NotFinal</td>
                                    }
                                    else
                                    {
                                        <td>Not Girilmedi</td>
                                    }
                                    <td class="text-end">
                                        <div class="actions ">
                                            <a href="javascript:;" class="btn btn-sm bg-success-light me-2 ">
                                                <i class="feather-eye"></i>
                                            </a>
                                            <a asp-controller="Not" asp-action="Ekle_Guncelle" asp-route-id="@not.Id" class="btn btn-sm bg-danger-light me-2">
                                                <i class="feather-edit"></i>
                                            </a>
                                            <a asp-controller="Not" asp-action="Sil" asp-route-id="@not.Id" class="btn btn-sm bg-danger-light">
                                                <i class="feather-trash-2"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@if (TempData["success"] != null)
{
    <script src="~/panel/plugins/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/panel/plugins/sweetalert/sweetalerts.min.js"></script>

    <script>
        var successMessage = "@TempData["success"]";

        Swal.fire({
            title: successMessage,
            icon: "success"
        });
    </script>
}
@section Scripts {
    <script>
        function aramaYap() {
            var ogrenciAdiInput, bolumAdiInput, ogrenciAdiFilter, bolumAdiFilter, table, tr, td, i;
            ogrenciAdiInput = document.getElementById("ogrenciAdiArama");
            bolumAdiInput = document.getElementById("bolumAdiArama");
            ogrenciAdiFilter = ogrenciAdiInput.value.toUpperCase();
            bolumAdiFilter = bolumAdiInput.value.toUpperCase();
            table = document.querySelector(".star-student");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                tdOgrenciAdi = tr[i].getElementsByTagName("td")[0];
                tdBolumAdi = tr[i].getElementsByTagName("td")[2];
                if (tdOgrenciAdi && tdBolumAdi) {
                    ogrenciAdiValue = tdOgrenciAdi.textContent || tdOgrenciAdi.innerText;
                    bolumAdiValue = tdBolumAdi.textContent || tdBolumAdi.innerText;
                    if (ogrenciAdiValue.toUpperCase().indexOf(ogrenciAdiFilter) > -1 && bolumAdiValue.toUpperCase().indexOf(bolumAdiFilter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
}