OBS_App/Areas/Admin/Controllers/DersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OBS_App.Data;
using OBS_App.Models;

namespace OBS_App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DersController : Controller
    {
        private readonly IdentityDataContext _context;

        public DersController(IdentityDataContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            var dersler = await _context.Dersler.Include(x => x.Ogretmens).Include(x => x.Bolum).ThenInclude(x => x.Ogrencisler).ToListAsync();
            ViewBag.Ogretmen = new SelectList(await _context.Ogretmenler.ToListAsync(), "Id", "OgretmenAdSoyad");
            return View(dersler);
        }

        public async Task<IActionResult> Ekle_Guncelle(int id)
        {
            if (id == 0)
            {
                ViewBag.Bolum = new SelectList(await _context.Bolumler.ToListAsync(), "Id", "BolumAd");
                ViewBag.Ogretmen = new SelectList(await _context.Ogretmenler.ToListAsync(), "Id", "OgretmenAdSoyad");
                return View();
            }
            else
            {
                ViewBag.Bolum = new SelectList(await _context.Bolumler.ToListAsync(), "Id", "BolumAd");
                ViewBag.Ogretmen = new SelectList(await _context.Ogretmenler.ToListAsync(), "Id", "OgretmenAdSoyad");
                var ders = await _context.Dersler.FirstOrDefaultAsync(x => x.Id == id);
                if (ders == null)
                {
                    // Hata Gönder
                    return NotFound();
                }
                return View(ders);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Ekle_Guncelle(Ders model, int id)
        {
            if (ModelState.IsValid)
            {
                var bolum = await _context.Bolumler
                                       .Include(x => x.Fakulte)
                                       .Include(x => x.Ogrencisler)
                                       .FirstOrDefaultAsync(x => x.Id == model.BolumId);
                model.FakulteId = bolum.FakulteId;
                model.Fakulte = bolum.Fakulte;

                if (id == 0)
                {

                    model.Ogrencisler = bolum.Ogrencisler;
                    model.OlusturmaTarihi = DateOnly.FromDateTime(DateTime.Today);

                    await _context.AddAsync(model);
                    _context.SaveChanges();
                    TempData["success"] = "Kayıt eklendi.";

                    return RedirectToAction("Index");
                }
                else
                {
                    _context.Update(model);
                    _context.SaveChanges();
                    TempData["success"] = "Kayıt güncellendi.";

                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.Bolum = new SelectList(await _context.Bolumler.ToListAsync(), "Id", "BolumAd");
                ViewBag.Ogretmen = new SelectList(await _context.Ogretmenler.ToListAsync(), "Id", "OgretmenAdSoyad");
                return View(model);
            }
        }

        // id ye göre db'den kayıt siliyor
        public IActionResult Sil(int id)
        {
            var ders = _context.Dersler.FirstOrDefault(x => x.Id == id);
            if (ders != null)
            {
                _context.Remove(ders);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Detay(int id)
        {
            var ders = await _context.Dersler
                    .Include(f => f.Ogrencisler)
                    .ToListAsync();
            var model = ders.FirstOrDefault(x => x.Id == id);

            return View(model);
        }
    }

}

OBS_App/Areas/Ogrenci/Controllers/DersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OBS_App.Models;
using System.Text.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace OBS_App.Areas.Ogrenci.Controllers
{
    [Area("Ogrenci")]
    public class DersController : BaseController
    {
        private readonly IdentityDataContext _context;
        private readonly UserManager<AppUser> _userManager;

        public DersController(IdentityDataContext context, UserManager<AppUser> userManager) : base(userManager, context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Derslerim()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                // Kullanıcının derslerini çek
                var ogrenci = _context.Ogrenciler.FirstOrDefault(d => d.OgrenciEposta == kullanıcı.Email);
                var dersler = _context.Ogrenciler
                    .Include(x => x.Dersler)
                    .ThenInclude(x => x.Ogretmens)
                    .Include(x => x.Notlar)
                    .Where(x => x.Id == ogrenci.Id)
                    .ToList();

                return View(dersler);
            }

            // Hata Gönder
            return View();
        }

        public async Task<IActionResult> DersProgrami()
        {

            return View();

        }
        public async Task<IActionResult> DersProgramiTakvim()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            var ogrenci = await _context.Ogrenciler.FirstOrDefaultAsync(x => x.OgrenciEposta == kullanıcı.Email);
            var dersler = await _context.Dersler.Where(x => x.Bolum.Id == ogrenci.BolumId).ToListAsync();
            return Json(dersler);


        }

        public async Task<IActionResult> SınavSonuc()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                // Kullanıcının derslerini çek
                var ogrenci = _context.Ogrenciler.FirstOrDefault(d => d.OgrenciEposta == kullanıcı.Email);
                var dersler = _context.Notlar.Include(x => x.Ogretmens).Include(x => x.Ders).Where(x => x.OgrencisId == ogrenci.Id).ToList();

                ViewBag.sınıfNotOrtalamaları = _context.Notlar
                    .Where(x => x.Ogrencis.BolumId == ogrenci.BolumId)
                    .GroupBy(x => x.Ders)
                    .Select(group => new
                    {
                        DersAdi = group.Key,
                        NotOdevOrtalamasi = group.Average(x => x.NotOdev),
                        NotVizeOrtalamasi = group.Average(x => x.NotVize),
                        NotFinalOrtalamasi = group.Average(x => x.NotFinal),
                        ToplamOrtalama = (group.Average(x => x.NotOdev) * 0.25 + group.Average(x => x.NotVize) * 0.35 + group.Average(x => x.NotFinal) * 0.40)
                    })
                    .ToList();

                return View(dersler);
            }

            // Hata Gönder
            return View();
        }

        public IActionResult SınavTakvim()
        {
            return View();
        }

    }
}

OBS_App/Areas/Ogretmen/Controllers/DersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OBS_App.Models;

namespace OBS_App.Areas.Ogretmen.Controllers
{
    [Area("Ogretmen")]
    public class DersController : BaseController
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IdentityDataContext _context;

        public DersController(UserManager<AppUser> userManager, IdentityDataContext context) : base(userManager, context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Ogretmen_Derslerim()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                var ogretmen = _context.Ogretmenler.FirstOrDefault(d => d.OgretmenEposta == kullanıcı.Email);
                var dersler = _context.Dersler.Include(x => x.Ogrencisler).Where(x => x.OgretmensId == ogretmen.Id).ToList();

                return View(dersler);
            }
            return View();
        }

        public async Task<IActionResult> DersProgramı()
        {
            var kullanıcı = await _userManager.GetUserAsync(User);
            if (kullanıcı != null)
            {
                var ogretmen = _context.Ogretmenler.FirstOrDefault(d => d.OgretmenEposta == kullanıcı.Email);
                var dersler = _context.Dersler
                    .Include(x => x.Fakulte)
                    .Include(x => x.Bolum)
					.OrderBy(x => x.DersGün == "Pazartesi" ? 1 :
								  x.DersGün == "Salı" ? 2 :
								  x.DersGün == "Çarşamba" ? 3 :
								  x.DersGün == "Perşembe" ? 4 :
								  x.DersGün == "Cuma" ? 5 : 6)
					.Where(x => x.OgretmensId == ogretmen.Id)
                    .ToList();

                return View(dersler);
			}
			return View();
        }

    }
}

OBS_App/Areas/Ogrenci/Views/Ders/DersProgrami.cshtml
@{
    ViewData["Title"] = "DersProgramı";
}

<h2>Ders Programı</h2>

<div class="content container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        !function ($) {
            "use strict";

            // CalendarApp sınıfı tanımlanıyor
            var CalendarApp = function () {
                // Takvim öğesini seçmek için jQuery ile DOM öğesi seçici atanıyor
                this.$calendar = $('#calendar');
            };


            // CalendarApp sınıfının prototipine init() metodu ekleniyor
            CalendarApp.prototype.init = function () {
                var defaultEventss = [];
                $.ajax({
                    url: '@Url.Action("DersProgramiTakvim", "Ders")',
                    method: 'GET',
                    success: function (data) {
                        console.log(data);

                        var today = new Date($.now());

                        data.forEach(function (ders) {
                            var events = {

                                title: ders.dersAd,
                                start: today,
                                end: today,
                                className: 'bg-primary'
                            };
                            defaultEventss.push(events);
                        });
                        createCalendar();
                    },
                    error: function (xhr, status, error) {

                        console.error(error);

                    }
                });

                function createCalendar() {
                    console.log(defaultEventss);

                    $('#calendar').fullCalendar({
                        // Takvim görünümü ve düzenlemeye izin verilmeyen diğer ayarlar belirleniyor
                        defaultView: 'month',
                        header: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,agendaWeek,agendaDay'
                        },
                        events: defaultEventss, // Varsayılan etkinlikler takvime atanıyor
                        editable: false, // Takvimde düzenlemeye izin verilmiyor
                        droppable: false, // Etkinliklerin sürüklenip bırakılmasına izin verilmiyor
                        eventLimit: false, // Etkinlik sınırlaması devre dışı bırakılıyor
                        selectable: false // Etkinlik seçilebilirliği devre dışı bırakılıyor
                    });
                }

                // Yeni etkinlik eklemek için düğmeye tıklama olayı ekleniyor
                $('#addEventBtn').on('click', function () {
                    // Kullanıcıdan etkinlik adını almak için bir iletişim kutusu açılıyor
                    var categoryName = prompt("Etkinlik adı girin:");
                    if (categoryName && categoryName.trim().length > 0) {
                        // Kullanıcının girdiği adı kullanarak yeni bir etkinlik oluşturuluyor
                        var newEvent = {
                            title: categoryName,
                            start: today, // Yeni etkinliğin başlangıç tarihi bugün
                            className: 'bg-primary' // Yeni etkinliğin sınıfı (renk)
                        };
                        // Yeni etkinlik takvime ekleniyor
                        $('#calendar').fullCalendar('renderEvent', newEvent, true);
                    }
                });
            };

            // CalendarApp sınıfı ve prototipi tanımlandıktan sonra, bir örneği oluşturuluyor
            $.CalendarApp = new CalendarApp;
            $.CalendarApp.Constructor = CalendarApp;

        }(window.jQuery),

            // Oluşturulan CalendarApp örneği başlatılıyor
            function ($) {
                "use strict";
                $.CalendarApp.init(); // CalendarApp başlatılıyor
            }(window.jQuery);


    </script>
}

OBS_App/Areas/Ogrenci/Views/Ders/Derslerim.cshtml
@{
    ViewData["Title"] = "Derslerim";
}
@model IEnumerable<Ogrencis>

<div class="student-group-form">
    <div class="row">
        <div class="col-lg-5 col-md-7">
            <div class="form-group">
                <input type="text" class="form-control" id="dersArama" placeholder="Ders İsmine Göre Ara ..." oninput="aramaYap()">
            </div>
        </div>
        <div class="col-lg-5 col-md-7">
            <div class="form-group">
                <input type="text" class="form-control" id="dersHocasıArama" placeholder="Ders Hocasına Göre Ara ..." oninput="aramaYap()">
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body">

                <div class="page-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="page-title">Dersler</h3>
                        </div>
                    </div>
                </div>

                <table class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
                    <thead class="student-thread">
                        <tr>
                            <th>Ders Adı</th>
                            <th>Ders Hocası</th>
                            <th>Ders Kredi</th>
                            <th>Ders Akts</th>
                            <th>Ders Ödev</th>
                            <th>Ders Vize</th>
                            <th>Ders Final</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var ogrenci in Model)
                        {
                            @foreach (var ders in ogrenci.Dersler)
                            {
                                <tr>
                                    <td>@ders.DersAd</td>
                                    <td>
                                        <h2 class="table-avatar">
                                            <a class="avatar avatar-sm me-2"><img class="avatar-img rounded-circle" src="~/img/@ders.Ogretmens?.OgretmenFotograf" alt="Ogretmen Image"></a>
                                            <a>@ders.Ogretmens?.OgretmenAd @ders.Ogretmens?.OgretmenSoyad</a>
                                        </h2>
                                    </td>
                                    <td>@ders.DersKredi</td>
                                    <td>@ders.DersAkts</td>

                                    @foreach (var not in ders.notlar)
                                    {
                                        @if (not.NotOdev != null)
                                        {
                                            <td>@not.NotOdev</td>
                                        }
                                        else
                                        {
                                            <td>Not Girilmedi</td>
                                        }
                                        @if (not.NotVize != null)
                                        {
                                            <td>@not.NotVize</td>
                                        }
                                        else
                                        {
                                            <td>Not Girilmedi</td>
                                        }
                                        @if (not.NotFinal != null)
                                        {
                                            <td>@not.NotFinal</td>
                                        }
                                        else
                                        {
                                            <td>Not Girilmedi</td>
                                        }
                                    }

                                    @if (ders.notlar.Count() == 0)
                                    {
                                        <td>Not Girilmedi</td>
                                        <td>Not Girilmedi</td>
                                        <td>Not Girilmedi</td>
                                    }

                                </tr>
                            }
                        }

                    </tbody>
                </table>
            </div>
            @if (Model.Count() == 0)
            {
                <div class="blog grid-blog flex-fill">
                    <h3 class="text-danger" style="text-align:center"> Ders Bulunmamaktadır! </h3>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function aramaYap() {
            var dersAdiInput, dersHocasıInput, dersAdiFilter, dersHocasıFilter, table, tr, td, i;
            dersAdiInput = document.getElementById("dersArama");
            dersHocasıInput = document.getElementById("dersHocasıArama");
            dersAdiFilter = dersAdiInput.value.toUpperCase();
            dersHocasıFilter = dersHocasıInput.value.toUpperCase();
            table = document.querySelector(".star-student");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                tdDersAdi = tr[i].getElementsByTagName("td")[0];
                tdDersHocası = tr[i].getElementsByTagName("td")[1];
                if (tdDersAdi && tdDersHocası) {
                    dersAdiValue = tdDersAdi.textContent || tdDersAdi.innerText;
                    dersHocasıValue = tdDersHocası.textContent || tdDersHocası.innerText;
                    if (dersAdiValue.toUpperCase().indexOf(dersAdiFilter) > -1 && dersHocasıValue.toUpperCase().indexOf(dersHocasıFilter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
}

OBS_App/Areas/Ogrenci/Views/Ders/SınavSonuc.cshtml
@{
	ViewData["Title"] = "SınavSonuc";
    int ders_sayı = 0;
}
@model List<Not>

<div class="content container-fluid">
    <div class="row">
        @if (Model.Count() != 0)
        {
            @foreach (var ders in Model)
            {

                // Notların ağırlıklı ortalamasını hesapla
                decimal notOrtalamasi = CalculateWeightedAverage(ders);
                string harfNotu = CalculateLetterGrade(notOrtalamasi);

                <div class="col-sm-6 col-lg-4 col-xl-4 d-flex">
                    <div class="card invoices-grid-card w-100">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <a style="font-weight:bold; font-size:15px; ">@ders.Ders?.DersAd</a>
                            @if (ders.NotOdev != null && ders.NotVize != null && ders.NotFinal != null)
                                @if (notOrtalamasi >= 50)
                                {
                                    <h6 class="text-end text-success">Geçtiniz</h6>
                                }
                                else
                                {
                                    <h6 class="text-end text-danger">Kaldınız</h6>
                                }
                        </div>
                        <div class="card-middle">
                            <h2 class="card-middle-avatar">
                                
                                <a><img class="avatar avatar-sm me-2 avatar-img rounded-circle" src="~/img/@ders.Ogretmens?.OgretmenFotograf" alt="User Image"> @ders.Ogretmens?.OgretmenAdSoyad</a>
                                
                            </h2>
                        </div>
                        <div class="card-body">

                            <div class="progress progress-md">
                                <div class="progress-bar bg-success" role="progressbar" style="width: @Math.Round(notOrtalamasi)%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                            <table style="width:100%;">
                                <tbody>
                                    <tr>
                                        <td style="font-size:10px;  text-align:center;">
                                            <div>
                                                Ortalamanız : <span style="color:#00711b">@notOrtalamasi</span>
                                            </div>
                                        </td>
                                        @if (ViewBag.sınıfNotOrtalamaları[ders_sayı].ToplamOrtalama != null)
                                        {
                                            <td style="font-size:10px; text-align:center;">
                                                Sınıf Ortalaması : <span style="color:#00711b">@Math.Round((ViewBag.sınıfNotOrtalamaları[ders_sayı].ToplamOrtalama), 2)</span>
                                            </td>
                                        }
                                        else
                                        {
                                            <td style="font-size:10px; text-align:center;">
                                                Sınıf Ortalaması : <span style="color:#00711b">Girilmedi</span>
                                            </td>
                                        }
                                        @{ders_sayı = ders_sayı + 1;}
                                    </tr>
                                </tbody>
                            </table>
                            <br>

                            <table style="text-align:center" class="table">
                                <tr>
                                    <td><i class="fas fa-pencil"></i> <b>Sınav<b></td>
                                    <td><i class="fas fa-square-poll-vertical"></i> <b>Not<b></td>
                                    <td><i class="far fa-calendar-alt"></i> <b>Tarih<b></td>
                                    <td><i class="far fa-clock"></i> <b>Saat<b></td>
                                </tr>
                                <tr>
                                    <td><b>Ödev<b></td>
                                    <td>@ders.NotOdev</td>
                                    <td>@ders.NotOdevTarih</td>
                                    <td>@ders.NotOdevSaat</td>
                                </tr>
                                <tr>
                                    <td><b>Vize<b></td>
                                    <td>@ders.NotVize</td>
                                    <td>@ders.NotVizeTarih</td>
                                    <td>@ders.NotVizeSaat</td>
                                </tr>
                                <tr>
                                    <td><b>Final<b></td>
                                    <td>@ders.NotFinal</td>
                                    <td>@ders.NotFinalTarih</td>
                                    <td>@ders.NotFinalSaat</td>
                                </tr>
                            </table>


                        </div>
                        <div class="card-footer">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                    @if (ders.NotOdev != null && ders.NotVize != null && ders.NotFinal != null)
                                    {
                                        <span class="badge bg-success-dark">Bitti</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-gradient-warning">Devam Ediyor</span>
                                    }
                                </div>
                                <div class="col text-end">
                                    <h5 style="color:royalblue">Harf Notu: @CalculateLetterGrade(notOrtalamasi)</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="blog grid-blog flex-fill">
                <h3 class="text-danger" style="text-align:center"> Sınav Bilgisi Bulunmamaktadır! </h3>
            </div>
        }
    </div>
</div>

@functions {
    public decimal CalculateWeightedAverage(Not ders)
    {
        decimal toplamNot = 0;
        decimal toplamAgirlik = 0;

        if (ders.NotOdev.HasValue)
        {
            toplamNot += ders.NotOdev.Value * 0.25m;
            toplamAgirlik += 0.25m;
        }

        if (ders.NotVize.HasValue)
        {
            toplamNot += ders.NotVize.Value * 0.35m;
            toplamAgirlik += 0.35m;
        }

        if (ders.NotFinal.HasValue)
        {
            toplamNot += ders.NotFinal.Value * 0.40m;
            toplamAgirlik += 0.40m;
        }

        decimal ortalama = toplamAgirlik != 0 ? toplamNot / toplamAgirlik : 0;
        return Math.Round(ortalama, 2); // Ondalık basamakları 2'ye yuvarla
    }


    private string CalculateLetterGrade(decimal ortalama)
    {
        if (ortalama >= 90)
            return "AA";
        else if (ortalama >= 80)
            return "BA";
        else if (ortalama >= 75)
            return "BB";
        else if (ortalama >= 70)
            return "CB";
        else if (ortalama >= 60)
            return "CC";
        else if (ortalama >= 50)
            return "DC";
        else if (ortalama >= 40)
            return "DD";
        else if (ortalama >= 30)
            return "FD";
        else
            return "FF";
    }
}

OBS_App/Areas/Ogrenci/Views/Ders/SınavTakvim.cshtml
@{
    ViewData["Title"] = "SınavTakvim";
}

<h2>Sınav Takvim</h2>
<div class="content container-fluid">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="card">
				<div class="card-body">
					<div id="calendar"></div>
				</div>
			</div>
		</div>
	</div>
</div>